allowBuilds:
  '@prisma/engines': true
  prisma: true
  sharp: true
  tesseract.js: false
  unrs-resolver: true

ignoredBuiltDependencies:
  - unrs-resolver

onlyBuiltDependencies:
  - '@prisma/engines'
  - prisma
  - sharp

overrides:
  deepmerge-ts: 8.0.2
  mysql2: 3.22.0
