export const TRANSACTION_DESCRIPTION_MIN_LENGTH = 2;
export const TRANSACTION_DESCRIPTION_MAX_LENGTH = 100;
export const TRANSACTION_MAX_AMOUNT_CENTS = 1_000_000_000;
export const TRANSACTION_MIN_YEAR = 2000;
export const TRANSACTION_MAX_YEAR = 2100;
